name: store_flutter_progect
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  


  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  geolocator: ^10.1.0
  weather: ^3.1.1
  intl: ^0.19.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
flutter:

  uses-material-design: true

  assets:
    - imag/
    - asset/
   
